# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        #Dialog.showFullScreen()
        self.start_button = QtWidgets.QLabel(Dialog)
        self.start_button.setGeometry(QtCore.QRect(490, 440, 391, 141))
        self.start_button.setText("")
        self.start_button.setPixmap(QtGui.QPixmap("ANIM_INTRO/Intro/start.png"))
        self.start_button.setScaledContents(True)
        self.start_button.setObjectName("start_button")
        self.exit_button = QtWidgets.QLabel(Dialog)
        self.exit_button.setGeometry(QtCore.QRect(570, 590, 231, 71))
        self.exit_button.setText("")
        self.exit_button.setPixmap(QtGui.QPixmap("ANIM_INTRO/Intro/exit.png"))
        self.exit_button.setScaledContents(True)
        self.exit_button.setObjectName("exit_button")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(520, 380, 331, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.fond = QtWidgets.QLabel(Dialog)
        self.fond.setGeometry(QtCore.QRect(130, 80, 1171, 801))
        self.fond.setObjectName("fond")
        self.fond.raise_()
        self.start_button.raise_()
        self.exit_button.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setText(_translate("Dialog", "Entrez nom Dresseur"))
        self.fond.setText(_translate("Dialog", "TextLabel"))
